name: Docker Build

on:
  schedule:
    - cron: "0 0 * * 6"
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  packages: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set tags
        id: tags
        run: |
          echo "build_date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/baseimage-ubuntu
          tags: |
            type=raw,value=latest,enable=${{ github.event_name != 'pull_request' }}
            type=raw,value=${{ steps.tags.outputs.build_date }}
            type=raw,value=noble

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          provenance: false # prevent unknown architecture
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: BUILD_VERSION=${{ steps.tags.outputs.build_date }}
